


from flask import Flask, render_template, redirect, url_for, request, flash
from models import PROJECT_POSTS ,db
from add_new_porc import add_new_proc
from edit_all_proc import delete_proc ,edit_proc

import os
from flask_ckeditor import CKEditor
from werkzeug.utils import secure_filename
import smtplib


app = Flask(__name__)
# app.config['SQLALCHEMY_DATABASE_URI'] = 'postgresql+psycopg://go_todo_task_db_user:z3YSJb1og6V5aDVXuJqv9Kgsn7VgBpTO@dpg-d20liqndiees739m4op0-a.oregon-postgres.render.com/go_todo_task_db'
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///my_databse.db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
app.register_blueprint(edit_proc,url_prefix="")
app.register_blueprint(delete_proc,url_prefix="")

ckeditor = CKEditor(app)
app.secret_key = 'your_secret_key'
# Set config before blueprint registration
app.config['UPLOAD_FOLDER'] = 'static/uploads'

# Initialize database with app
db.init_app(app)

# Import blueprint after app and db are ready
from add_new_porc import add_new_proc

# Register blueprint
app.register_blueprint(add_new_proc)


    
@app.route('/', methods=['GET', 'POST'])
def home_page():
    p = PROJECT_POSTS.query.all()
    print(p)
    if request.method == 'POST':
        name = request.form.get('name')
        subject = request.form.get('subject')
        phoneno = request.form.get('phoneno')
        email = request.form.get('email')
        msg = request.form.get('msg')
        print(name, email, phoneno, subject, msg)

        sender_mail = "maaz.irshad.siddiqui@gmail.com"
        password = "tvud sggg rdle ywll"
        message = f"""Subject: New Portfolio Contact Form Submission

Dear Admin,
You have received a new message via the contact form on your portfolio website.
Please find the details below:

------------------------------
Name     : {name}
Email    : {email}
Phone No : {phoneno}

Message:
{msg}
------------------------------

This message was automatically generated by your website's contact form.
Please respond to the sender at your earliest convenience.

Best regards,  
Portfolio Website Notification System
"""

        with smtplib.SMTP_SSL("smtp.gmail.com", port=465) as connection:
            connection.login(user=sender_mail, password=password)
            connection.sendmail(
                from_addr=sender_mail,
                to_addrs='siddiqui.maaz79@gmail.com',
                msg=message.encode("utf-8")
            )
        print("Mail Sent")

    return render_template('index.html', all_post=p)




@app.route("/maaz-project/<id>")
def maaz_project(id):
    print('+=========================================REACHED View Project=========================================+')
    post = PROJECT_POSTS.query.filter_by(id=int(id)).first()
    return render_template("specific-project.html", post=post)





if __name__ == '__main__':
    with app.app_context():
        db.create_all()  # Create tables before first request
    app.run(debug=True)
